### PR TITLE
only return meta-log information if that key exists

### LINKED ISSUE #2: no versions are returned when meta('log') does not exist
All projects on our devpi server that have versions linking to /root/pypi  do not have log meta entry (i.e. no info about when uploaded). The available versions should still return a list, even when additional meta information does not exist.

### PR DESCRIPTION
**Pull request by ms-ai**
Fixes https://github.com/bcicen/devpi-tools/issues/2

### CODE REVIEW

**Comment by bcicen** [comment]
looks good; thanks @ms-ai !

**Comment by ms-ai** [comment]
Can you cut a new release with this fix?

**Comment by bcicen** [comment]
@ms-ai v0.5.2 now pushed

**Comment by ms-ai** [comment]
Thx!

**Comment by ms-ai** [comment]
Sorry to bother you again, but pip install devpi-tools==0.5.2  returns with:
```
ERROR: Could not find a version that satisfies the requirement devpi-tools==0.5.2 (from versions: 0.5.2.linux-x86_64, 0.2, 0.3, 0.4, 0.5.1)
ERROR: No matching distribution found for devpi-tools==0.5.2
```

I get that error message on both, linux and windows.

**Comment by bcicen** [comment]
apologies, build was a bit broken -- now fixed and ```pip install devpi-tools==0.5.3``` should work

**Pull request merged**
